name: Lint Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Commitlint
        run: |
          npm install --save-dev @commitlint/{config-conventional,cli}

      - name: Lint Commits
        run: |
          npx commitlint --from=HEAD~1 --to=HEAD --config '{ "extends": ["@commitlint/config-conventional"] }'
