name: Conventional Commits

on:
  push:
    branches:
      - '**'  # Esto aplica a todas las ramas
  pull_request:
    branches:
      - '**'  # Esto aplica a todas las ramas

jobs:
  conventional-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Obtener todas las ramas y la historia completa

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install commitlint
        run: |
          npm install -g @commitlint/config-conventional @commitlint/cli

      - name: Create commitlint configuration file
        run: |
          echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js

      - name: Check commit messages
        run: |
          BASE_REF=${{ github.event_name == 'push' && 'master' || github.base_ref }}  # Cambia 'main' si deseas otra rama base
          git fetch origin $BASE_REF  # Asegúrate de que la rama base se haya recuperado
          git log origin/$BASE_REF..HEAD --pretty=format:%s | commitlint

      - name: Check PR title
        if: github.event_name == 'pull_request'
        run: |
          echo "${{ github.event.pull_request.title }}" | commitlint
